
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourmysqlpassword
      MYSQL_DATABASE: webshop
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nestjs-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - nestjs-network

  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL}
      - PORT=${PORT}
      - FE_URL=${FE_URL}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=yourmysqlpassword
      - MYSQL_DB_NAME=webshop
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - BCRYPT_SALT_ROUND=${BCRYPT_SALT_ROUND}
      - OTP_SIZE=${OTP_SIZE}
      - OTP_TIMEOUT=${OTP_TIMEOUT}
      - OTP_TIME_LIMIT=${OTP_TIME_LIMIT}
      - OTP_LIMIT=${OTP_LIMIT}
    depends_on:
      - mysql
      - redis
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local