import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1737047191982 implements MigrationInterface {
    name = 'Migrations1737047191982'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`active_storage_blobs\` (\`id\` varchar(36) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`key\` varchar(255) NOT NULL, \`filename\` varchar(255) NOT NULL, \`content_type\` varchar(255) NOT NULL, \`metadata\` text NOT NULL, \`byte_size\` int NOT NULL, \`checksum\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`active_storage_attachments\` (\`id\` varchar(36) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(255) NOT NULL, \`record_type\` varchar(255) NOT NULL, \`activeStorageBlobId\` varchar(36) NULL, \`mediaItemId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`banners\` (\`id\` varchar(36) NOT NULL, \`descriptions\` text NOT NULL, \`start_date\` datetime NOT NULL, \`end_date\` datetime NOT NULL, \`number_order\` int NOT NULL, \`url\` varchar(255) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`media_items\` (\`id\` varchar(36) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`resource_type\` varchar(255) NOT NULL, \`media_type\` int NOT NULL, \`media_url\` text NOT NULL, \`productId\` varchar(36) NULL, \`bannerId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`parentCategoryId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`category_tinies\` (\`id\` varchar(36) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`categoryId\` varchar(36) NULL, \`productId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`discount_settings\` (\`id\` varchar(36) NOT NULL, \`custom_discount_value\` int NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`productId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_settings\` (\`id\` varchar(36) NOT NULL, \`free_ship_amount\` int NOT NULL, \`free_ship_number\` int NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`prefectures\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`postcode\` varchar(255) NOT NULL, \`shipping_fee\` int NOT NULL, \`kind\` int NOT NULL, \`label\` varchar(255) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`shippingSettingId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`store_prefectures\` (\`id\` varchar(36) NOT NULL, \`shipping_fee\` int NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`prefectureId\` varchar(36) NULL, \`storeId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bill_logs\` (\`id\` varchar(36) NOT NULL, \`content\` text NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`billId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_companies\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`name\` varchar(255) NULL, \`phone\` varchar(12) NULL, \`url\` varchar(255) NOT NULL, \`memo\` text NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_notices\` (\`id\` varchar(36) NOT NULL, \`document_number\` varchar(255) NOT NULL, \`subject\` text NOT NULL, \`content\` text NOT NULL, \`memo\` text NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`shippingCompanyId\` varchar(36) NULL, \`orderItemId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_maker_managers\` (\`id\` varchar(36) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`userId\` varchar(36) NULL, \`shippingInstructionId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_instructions\` (\`id\` varchar(36) NOT NULL, \`shipping_department\` int NOT NULL, \`shipping_source\` int NOT NULL, \`email\` varchar(255) NOT NULL, \`subject\` text NOT NULL, \`content\` text NOT NULL, \`memo\` text NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`orderItemId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` varchar(36) NOT NULL, \`price\` int NOT NULL, \`status\` int NOT NULL, \`shipping_date\` datetime NOT NULL, \`order_type\` int NOT NULL, \`quantity\` int NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`orderId\` varchar(36) NULL, \`cartItemId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` varchar(36) NOT NULL, \`orderer_type\` varchar(255) NOT NULL, \`receiver_type\` varchar(255) NOT NULL, \`order_status\` varchar(255) NOT NULL DEFAULT '0', \`shipping_status\` varchar(255) NOT NULL DEFAULT '0', \`order_id\` varchar(255) NOT NULL, \`order_date\` datetime NOT NULL, \`order_at\` datetime NOT NULL, \`memo\` text NOT NULL, \`order_type\` int NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`billId\` varchar(36) NULL, \`userId\` varchar(36) NULL, \`orderer_id\` varchar(36) NULL, \`receiver_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bills\` (\`id\` varchar(36) NOT NULL, \`status\` int NOT NULL, \`export_at\` datetime NOT NULL, \`bill_id\` varchar(255) NOT NULL, \`reduced_taxable_amount\` int NOT NULL, \`reduced_tax\` int NOT NULL, \`taxable_amount\` int NOT NULL, \`tax\` int NOT NULL, \`shipping_fee\` int NOT NULL, \`amount\` int NOT NULL, \`discount\` int NOT NULL, \`total_amount\` int NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`color_types\` (\`id\` varchar(36) NOT NULL, \`color_code\` varchar(255) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`size_types\` (\`id\` varchar(36) NOT NULL, \`size_code\` varchar(255) NOT NULL, \`size_type\` varchar(255) NOT NULL DEFAULT '0', \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_type_resources\` (\`id\` varchar(36) NOT NULL, \`quantity\` int UNSIGNED NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`productTypeId\` varchar(36) NULL, \`productResourceId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_types\` (\`id\` varchar(36) NOT NULL, \`quantity\` int UNSIGNED NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`productId\` varchar(36) NULL, \`colorTypeId\` varchar(36) NULL, \`sizeTypeId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bill_items\` (\`id\` varchar(36) NOT NULL, \`quantity\` int NOT NULL, \`price\` int NOT NULL, \`order_id\` varchar(255) NOT NULL, \`order_at\` datetime NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`billGroupId\` varchar(36) NULL, \`productTypeId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bill_groups\` (\`id\` varchar(36) NOT NULL, \`reduced_taxable_amount\` int NOT NULL, \`reduced_tax\` int NOT NULL, \`taxable_amount\` int NOT NULL, \`tax\` int NOT NULL, \`shipping_fee\` int NOT NULL, \`amount\` int NOT NULL, \`discount\` int NOT NULL, \`total_amount\` int NOT NULL, \`order_type\` int NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`billId\` varchar(36) NULL, \`storeId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stores\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`name\` varchar(255) NULL, \`postcode\` varchar(8) NOT NULL, \`prefecture\` varchar(255) NULL, \`city\` varchar(255) NULL, \`street\` varchar(255) NULL, \`building\` varchar(255) NULL, \`status\` varchar(255) NOT NULL DEFAULT '0', \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_resources\` (\`id\` varchar(36) NOT NULL, \`resource_type\` varchar(255) NOT NULL, \`quantity\` int UNSIGNED NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`productId\` varchar(36) NULL, \`resource_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`favorites\` (\`id\` varchar(36) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`productId\` varchar(36) NULL, \`userId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`code\` varchar(255) NOT NULL, \`price\` int NOT NULL, \`quantity\` int UNSIGNED NOT NULL, \`quantity_alert\` int UNSIGNED NOT NULL, \`order_unit\` int NOT NULL, \`description\` text NOT NULL, \`status\` int NOT NULL, \`multiplication_rate\` int NOT NULL, \`discount\` float NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`campaign_products\` (\`id\` varchar(36) NOT NULL, \`discount_value\` int NOT NULL, \`product_type\` int NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`campaignId\` varchar(36) NULL, \`productId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`campaigns\` (\`id\` varchar(36) NOT NULL, \`start_date\` datetime NOT NULL, \`end_date\` datetime NOT NULL, \`campaign_type\` int NOT NULL, \`bought_count\` int NOT NULL, \`promotion_count\` int NOT NULL, \`name\` varchar(255) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cart_items\` (\`id\` varchar(36) NOT NULL, \`quantity\` int UNSIGNED NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT '0', \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`campaignId\` varchar(36) NULL, \`productId\` varchar(36) NULL, \`storeId\` varchar(36) NULL, \`productTypeId\` varchar(36) NULL, \`userId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`role\` varchar(255) NOT NULL DEFAULT 'user', \`name\` varchar(255) NULL, \`zipcode\` varchar(8) NULL, \`phone\` varchar(12) NULL, \`prefecture\` varchar(255) NULL, \`city\` varchar(255) NULL, \`street\` varchar(255) NULL, \`building\` varchar(255) NULL, \`encrypted_password\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT '0', \`current_sign_in_at\` datetime NULL, \`last_sign_in_at\` datetime NULL, \`tokens\` text NULL, \`provider\` varchar(255) NULL, \`uid\` varchar(255) NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`active_storage_attachments\` ADD CONSTRAINT \`FK_4f87551020bf812caef19badcdc\` FOREIGN KEY (\`activeStorageBlobId\`) REFERENCES \`active_storage_blobs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`active_storage_attachments\` ADD CONSTRAINT \`FK_079952e696964ef79a48278e150\` FOREIGN KEY (\`mediaItemId\`) REFERENCES \`media_items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`media_items\` ADD CONSTRAINT \`FK_e0a637a949ef1f6bab139974d7b\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`media_items\` ADD CONSTRAINT \`FK_ab328a62eec13540c806ba6190e\` FOREIGN KEY (\`bannerId\`) REFERENCES \`banners\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_ccde635bce518afe7c110858cc4\` FOREIGN KEY (\`parentCategoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_tinies\` ADD CONSTRAINT \`FK_9a21884881ffb067ef43dd3019b\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_tinies\` ADD CONSTRAINT \`FK_f01dc09539d0ae2d9773fc50051\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discount_settings\` ADD CONSTRAINT \`FK_2f119da8fa60c7c8aad79126368\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prefectures\` ADD CONSTRAINT \`FK_1278c051710dc0fd7405fb84b58\` FOREIGN KEY (\`shippingSettingId\`) REFERENCES \`shipping_settings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`store_prefectures\` ADD CONSTRAINT \`FK_19773ec3ea547c496dc31fc01be\` FOREIGN KEY (\`prefectureId\`) REFERENCES \`prefectures\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`store_prefectures\` ADD CONSTRAINT \`FK_b4dfaac3b0c598b50a235a921f7\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill_logs\` ADD CONSTRAINT \`FK_bf786e850d59e88b9af828c3a3d\` FOREIGN KEY (\`billId\`) REFERENCES \`bills\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_notices\` ADD CONSTRAINT \`FK_2dfae72a6ba6e15b07b43439ac3\` FOREIGN KEY (\`shippingCompanyId\`) REFERENCES \`shipping_companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_notices\` ADD CONSTRAINT \`FK_28df98dd352b0c2040ab3ff1131\` FOREIGN KEY (\`orderItemId\`) REFERENCES \`order_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_maker_managers\` ADD CONSTRAINT \`FK_7d19f5a0f354852b4208edb2bc7\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_maker_managers\` ADD CONSTRAINT \`FK_7523acc77bd43d31d5dc06cb0f5\` FOREIGN KEY (\`shippingInstructionId\`) REFERENCES \`shipping_instructions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_instructions\` ADD CONSTRAINT \`FK_370802cace0dd71f29f26b77d0f\` FOREIGN KEY (\`orderItemId\`) REFERENCES \`order_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_fe9000dbac97fbd6ea8e49abaae\` FOREIGN KEY (\`cartItemId\`) REFERENCES \`cart_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_1d654486f624b7805632a3585a3\` FOREIGN KEY (\`billId\`) REFERENCES \`bills\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_4f25ce83588f6f4fe87fdd5b8ea\` FOREIGN KEY (\`orderer_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2ba91092da6555355583985a5d5\` FOREIGN KEY (\`receiver_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_type_resources\` ADD CONSTRAINT \`FK_bbe2266f76a5aed6bba06b54235\` FOREIGN KEY (\`productTypeId\`) REFERENCES \`product_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_type_resources\` ADD CONSTRAINT \`FK_4f44d8a714206a362a645fd70d5\` FOREIGN KEY (\`productResourceId\`) REFERENCES \`product_resources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_types\` ADD CONSTRAINT \`FK_6ee30c7f441b25c115652193272\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_types\` ADD CONSTRAINT \`FK_39e2fed2bc5efe7beaf9a9151fe\` FOREIGN KEY (\`colorTypeId\`) REFERENCES \`color_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_types\` ADD CONSTRAINT \`FK_19e269f7a131480ac723b266473\` FOREIGN KEY (\`sizeTypeId\`) REFERENCES \`size_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill_items\` ADD CONSTRAINT \`FK_616323b8209c2a8dcd580dc6997\` FOREIGN KEY (\`billGroupId\`) REFERENCES \`bill_groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill_items\` ADD CONSTRAINT \`FK_5ffb12f501a26ca77aba2bbc018\` FOREIGN KEY (\`productTypeId\`) REFERENCES \`product_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill_groups\` ADD CONSTRAINT \`FK_ea12003830b5d4984a7447ac017\` FOREIGN KEY (\`billId\`) REFERENCES \`bills\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bill_groups\` ADD CONSTRAINT \`FK_0ba023c6e037a87903a16db29f7\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_resources\` ADD CONSTRAINT \`FK_89ea7a42e47e3a2936410c5fc81\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_resources\` ADD CONSTRAINT \`FK_9021bef1a81a04bbac06815ca6a\` FOREIGN KEY (\`resource_id\`) REFERENCES \`stores\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`FK_0c7bba48aac77ad13092685ba5b\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`FK_e747534006c6e3c2f09939da60f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`campaign_products\` ADD CONSTRAINT \`FK_2cc5383c964b1dee2fc9f2745d8\` FOREIGN KEY (\`campaignId\`) REFERENCES \`campaigns\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`campaign_products\` ADD CONSTRAINT \`FK_a904ec9711e7ca646a5ce7d48f3\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_ad75a47fb204506d0832d361f02\` FOREIGN KEY (\`campaignId\`) REFERENCES \`campaigns\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_72679d98b31c737937b8932ebe6\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_25c49e1f4630d8b791a120cdc3b\` FOREIGN KEY (\`storeId\`) REFERENCES \`stores\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_2fa1c1dfa09da5fcca155d97d65\` FOREIGN KEY (\`productTypeId\`) REFERENCES \`product_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_84e765378a5f03ad9900df3a9ba\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_84e765378a5f03ad9900df3a9ba\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_2fa1c1dfa09da5fcca155d97d65\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_25c49e1f4630d8b791a120cdc3b\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_72679d98b31c737937b8932ebe6\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_ad75a47fb204506d0832d361f02\``);
        await queryRunner.query(`ALTER TABLE \`campaign_products\` DROP FOREIGN KEY \`FK_a904ec9711e7ca646a5ce7d48f3\``);
        await queryRunner.query(`ALTER TABLE \`campaign_products\` DROP FOREIGN KEY \`FK_2cc5383c964b1dee2fc9f2745d8\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`FK_e747534006c6e3c2f09939da60f\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`FK_0c7bba48aac77ad13092685ba5b\``);
        await queryRunner.query(`ALTER TABLE \`product_resources\` DROP FOREIGN KEY \`FK_9021bef1a81a04bbac06815ca6a\``);
        await queryRunner.query(`ALTER TABLE \`product_resources\` DROP FOREIGN KEY \`FK_89ea7a42e47e3a2936410c5fc81\``);
        await queryRunner.query(`ALTER TABLE \`bill_groups\` DROP FOREIGN KEY \`FK_0ba023c6e037a87903a16db29f7\``);
        await queryRunner.query(`ALTER TABLE \`bill_groups\` DROP FOREIGN KEY \`FK_ea12003830b5d4984a7447ac017\``);
        await queryRunner.query(`ALTER TABLE \`bill_items\` DROP FOREIGN KEY \`FK_5ffb12f501a26ca77aba2bbc018\``);
        await queryRunner.query(`ALTER TABLE \`bill_items\` DROP FOREIGN KEY \`FK_616323b8209c2a8dcd580dc6997\``);
        await queryRunner.query(`ALTER TABLE \`product_types\` DROP FOREIGN KEY \`FK_19e269f7a131480ac723b266473\``);
        await queryRunner.query(`ALTER TABLE \`product_types\` DROP FOREIGN KEY \`FK_39e2fed2bc5efe7beaf9a9151fe\``);
        await queryRunner.query(`ALTER TABLE \`product_types\` DROP FOREIGN KEY \`FK_6ee30c7f441b25c115652193272\``);
        await queryRunner.query(`ALTER TABLE \`product_type_resources\` DROP FOREIGN KEY \`FK_4f44d8a714206a362a645fd70d5\``);
        await queryRunner.query(`ALTER TABLE \`product_type_resources\` DROP FOREIGN KEY \`FK_bbe2266f76a5aed6bba06b54235\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2ba91092da6555355583985a5d5\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_4f25ce83588f6f4fe87fdd5b8ea\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_1d654486f624b7805632a3585a3\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_fe9000dbac97fbd6ea8e49abaae\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`shipping_instructions\` DROP FOREIGN KEY \`FK_370802cace0dd71f29f26b77d0f\``);
        await queryRunner.query(`ALTER TABLE \`shipping_maker_managers\` DROP FOREIGN KEY \`FK_7523acc77bd43d31d5dc06cb0f5\``);
        await queryRunner.query(`ALTER TABLE \`shipping_maker_managers\` DROP FOREIGN KEY \`FK_7d19f5a0f354852b4208edb2bc7\``);
        await queryRunner.query(`ALTER TABLE \`shipping_notices\` DROP FOREIGN KEY \`FK_28df98dd352b0c2040ab3ff1131\``);
        await queryRunner.query(`ALTER TABLE \`shipping_notices\` DROP FOREIGN KEY \`FK_2dfae72a6ba6e15b07b43439ac3\``);
        await queryRunner.query(`ALTER TABLE \`bill_logs\` DROP FOREIGN KEY \`FK_bf786e850d59e88b9af828c3a3d\``);
        await queryRunner.query(`ALTER TABLE \`store_prefectures\` DROP FOREIGN KEY \`FK_b4dfaac3b0c598b50a235a921f7\``);
        await queryRunner.query(`ALTER TABLE \`store_prefectures\` DROP FOREIGN KEY \`FK_19773ec3ea547c496dc31fc01be\``);
        await queryRunner.query(`ALTER TABLE \`prefectures\` DROP FOREIGN KEY \`FK_1278c051710dc0fd7405fb84b58\``);
        await queryRunner.query(`ALTER TABLE \`discount_settings\` DROP FOREIGN KEY \`FK_2f119da8fa60c7c8aad79126368\``);
        await queryRunner.query(`ALTER TABLE \`category_tinies\` DROP FOREIGN KEY \`FK_f01dc09539d0ae2d9773fc50051\``);
        await queryRunner.query(`ALTER TABLE \`category_tinies\` DROP FOREIGN KEY \`FK_9a21884881ffb067ef43dd3019b\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_ccde635bce518afe7c110858cc4\``);
        await queryRunner.query(`ALTER TABLE \`media_items\` DROP FOREIGN KEY \`FK_ab328a62eec13540c806ba6190e\``);
        await queryRunner.query(`ALTER TABLE \`media_items\` DROP FOREIGN KEY \`FK_e0a637a949ef1f6bab139974d7b\``);
        await queryRunner.query(`ALTER TABLE \`active_storage_attachments\` DROP FOREIGN KEY \`FK_079952e696964ef79a48278e150\``);
        await queryRunner.query(`ALTER TABLE \`active_storage_attachments\` DROP FOREIGN KEY \`FK_4f87551020bf812caef19badcdc\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`cart_items\``);
        await queryRunner.query(`DROP TABLE \`campaigns\``);
        await queryRunner.query(`DROP TABLE \`campaign_products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP TABLE \`favorites\``);
        await queryRunner.query(`DROP TABLE \`product_resources\``);
        await queryRunner.query(`DROP TABLE \`stores\``);
        await queryRunner.query(`DROP TABLE \`bill_groups\``);
        await queryRunner.query(`DROP TABLE \`bill_items\``);
        await queryRunner.query(`DROP TABLE \`product_types\``);
        await queryRunner.query(`DROP TABLE \`product_type_resources\``);
        await queryRunner.query(`DROP TABLE \`size_types\``);
        await queryRunner.query(`DROP TABLE \`color_types\``);
        await queryRunner.query(`DROP TABLE \`bills\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP TABLE \`shipping_instructions\``);
        await queryRunner.query(`DROP TABLE \`shipping_maker_managers\``);
        await queryRunner.query(`DROP TABLE \`shipping_notices\``);
        await queryRunner.query(`DROP TABLE \`shipping_companies\``);
        await queryRunner.query(`DROP TABLE \`bill_logs\``);
        await queryRunner.query(`DROP TABLE \`store_prefectures\``);
        await queryRunner.query(`DROP TABLE \`prefectures\``);
        await queryRunner.query(`DROP TABLE \`shipping_settings\``);
        await queryRunner.query(`DROP TABLE \`discount_settings\``);
        await queryRunner.query(`DROP TABLE \`category_tinies\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP TABLE \`media_items\``);
        await queryRunner.query(`DROP TABLE \`banners\``);
        await queryRunner.query(`DROP TABLE \`active_storage_attachments\``);
        await queryRunner.query(`DROP TABLE \`active_storage_blobs\``);
    }

}
